apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-devtubeshop
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: keyPrefix
    value: <key-prefix-strategy>
auth:
  secretStore: devtubeshop-secrets
scopes:
  - catalogservice
  - identityservice
 